nohup python3 main.py CROSS2_NAZMUL_SVC_70 classificar > CROSS2_NAZMUL_SVC_70.log 2>&1
nohup python3 main.py CROSS2_NAZMUL_SVC_80 classificar > CROSS2_NAZMUL_SVC_80.log 2>&1
nohup python3 main.py CROSS2_NAZMUL_SVC_90 classificar > CROSS2_NAZMUL_SVC_90.log 2>&1
nohup python3 main.py CROSS2_YILDRIM_SVC_60 classificar > CROSS2_YILDRIM_SVC_60.log 2>&1
nohup python3 main.py CROSS2_YILDRIM_SVC_70 classificar > CROSS2_YILDRIM_SVC_70.log 2>&1
nohup python3 main.py CROSS2_YILDRIM_SVC_80 classificar > CROSS2_YILDRIM_SVC_80.log 2>&1
nohup python3 main.py CROSS2_YILDRIM_SVC_90 classificar > CROSS2_YILDRIM_SVC_90.log 2>&1
nohup python3 main.py YILDRIMJUNTO_CIFAR_SVC_60 classificar > YILDRIMJUNTO_CIFAR_SVC_60.log 2>&1
nohup python3 main.py YILDRIMJUNTO_CIFAR_SVC_70 classificar > YILDRIMJUNTO_CIFAR_SVC_70.log 2>&1
nohup python3 main.py YILDRIMJUNTO_CIFAR_SVC_80 classificar > YILDRIMJUNTO_CIFAR_SVC_80.log 2>&1
nohup python3 main.py YILDRIMJUNTO_CIFAR_SVC_90 classificar > YILDRIMJUNTO_CIFAR_SVC_90.log 2>&1
nohup python3 main.py YILDRIMJUNTO_NAZMUL_SVC_60 classificar > YILDRIMJUNTO_NAZMUL_SVC_60.log 2>&1
nohup python3 main.py YILDRIMJUNTO_NAZMUL_SVC_70 classificar > YILDRIMJUNTO_NAZMUL_SVC_70.log 2>&1
nohup python3 main.py YILDRIMJUNTO_NAZMUL_SVC_80 classificar > YILDRIMJUNTO_NAZMUL_SVC_80.log 2>&1
nohup python3 main.py YILDRIMJUNTO_NAZMUL_SVC_90 classificar > YILDRIMJUNTO_NAZMUL_SVC_90.log 2>&1
nohup python3 main.py YILDRIMJUNTO_YILDRIM_SVC_60 classificar > YILDRIMJUNTO_YILDRIM_SVC_60.log 2>&1
nohup python3 main.py YILDRIMJUNTO_YILDRIM_SVC_70 classificar > YILDRIMJUNTO_YILDRIM_SVC_70.log 2>&1
nohup python3 main.py YILDRIMJUNTO_YILDRIM_SVC_80 classificar > YILDRIMJUNTO_YILDRIM_SVC_80.log 2>&1
nohup python3 main.py YILDRIMJUNTO_YILDRIM_SVC_90 classificar > YILDRIMJUNTO_YILDRIM_SVC_90.log 2>&1
nohup python3 main.py CROSS3_CIFAR_SVC_60 classificar > CROSS3_CIFAR_SVC_60.log 2>&1
nohup python3 main.py CROSS3_CIFAR_SVC_70 classificar > CROSS3_CIFAR_SVC_70.log 2>&1
nohup python3 main.py CROSS3_CIFAR_SVC_80 classificar > CROSS3_CIFAR_SVC_80.log 2>&1
nohup python3 main.py CROSS3_CIFAR_SVC_90 classificar > CROSS3_CIFAR_SVC_90.log 2>&1
nohup python3 main.py CROSS3_NAZMUL_SVC_60 classificar > CROSS3_NAZMUL_SVC_60.log 2>&1
nohup python3 main.py CROSS3_NAZMUL_SVC_70 classificar > CROSS3_NAZMUL_SVC_70.log 2>&1
nohup python3 main.py CROSS3_NAZMUL_SVC_80 classificar > CROSS3_NAZMUL_SVC_80.log 2>&1
nohup python3 main.py CROSS3_NAZMUL_SVC_90 classificar > CROSS3_NAZMUL_SVC_90.log 2>&1
nohup python3 main.py CROSS3_YILDRIM_SVC_60 classificar > CROSS3_YILDRIM_SVC_60.log 2>&1
nohup python3 main.py CROSS3_YILDRIM_SVC_70 classificar > CROSS3_YILDRIM_SVC_70.log 2>&1
nohup python3 main.py CROSS3_YILDRIM_SVC_80 classificar > CROSS3_YILDRIM_SVC_80.log 2>&1
nohup python3 main.py CROSS3_YILDRIM_SVC_90 classificar > CROSS3_YILDRIM_SVC_90.log 2>&1 &