nohup python3 main.py YILDRIM_CIFAR_SVC_60 classificar > YILDRIM_CIFAR_SVC_60.log 2>&1
nohup python3 main.py YILDRIM_CIFAR_SVC_70 classificar > YILDRIM_CIFAR_SVC_70.log 2>&1
nohup python3 main.py YILDRIM_CIFAR_SVC_80 classificar > YILDRIM_CIFAR_SVC_80.log 2>&1
nohup python3 main.py YILDRIM_CIFAR_SVC_90 classificar > YILDRIM_CIFAR_SVC_90.log 2>&1
nohup python3 main.py YILDRIM_NAZMUL_SVC_60 classificar > YILDRIM_NAZMUL_SVC_60.log 2>&1
nohup python3 main.py YILDRIM_NAZMUL_SVC_70 classificar > YILDRIM_NAZMUL_SVC_70.log 2>&1
nohup python3 main.py YILDRIM_NAZMUL_SVC_80 classificar > YILDRIM_NAZMUL_SVC_80.log 2>&1
nohup python3 main.py YILDRIM_NAZMUL_SVC_90 classificar > YILDRIM_NAZMUL_SVC_90.log 2>&1
nohup python3 main.py YILDRIM_YILDRIM_SVC_60 classificar > YILDRIM_YILDRIM_SVC_60.log 2>&1
nohup python3 main.py YILDRIM_YILDRIM_SVC_70 classificar > YILDRIM_YILDRIM_SVC_70.log 2>&1
nohup python3 main.py YILDRIM_YILDRIM_SVC_80 classificar > YILDRIM_YILDRIM_SVC_80.log 2>&1
nohup python3 main.py YILDRIM_YILDRIM_SVC_90 classificar > YILDRIM_YILDRIM_SVC_90.log 2>&1
nohup python3 main.py CROSS1_CIFAR_SVC_60 classificar > CROSS1_CIFAR_SVC_60.log 2>&1
nohup python3 main.py CROSS1_CIFAR_SVC_70 classificar > CROSS1_CIFAR_SVC_70.log 2>&1
nohup python3 main.py CROSS1_CIFAR_SVC_80 classificar > CROSS1_CIFAR_SVC_80.log 2>&1
nohup python3 main.py CROSS1_CIFAR_SVC_90 classificar > CROSS1_CIFAR_SVC_90.log 2>&1
nohup python3 main.py CROSS1_NAZMUL_SVC_60 classificar > CROSS1_NAZMUL_SVC_60.log 2>&1
nohup python3 main.py CROSS1_NAZMUL_SVC_70 classificar > CROSS1_NAZMUL_SVC_70.log 2>&1
nohup python3 main.py CROSS1_NAZMUL_SVC_80 classificar > CROSS1_NAZMUL_SVC_80.log 2>&1
nohup python3 main.py CROSS1_NAZMUL_SVC_90 classificar > CROSS1_NAZMUL_SVC_90.log 2>&1
nohup python3 main.py CROSS1_YILDRIM_SVC_60 classificar > CROSS1_YILDRIM_SVC_60.log 2>&1
nohup python3 main.py CROSS1_YILDRIM_SVC_70 classificar > CROSS1_YILDRIM_SVC_70.log 2>&1
nohup python3 main.py CROSS1_YILDRIM_SVC_80 classificar > CROSS1_YILDRIM_SVC_80.log 2>&1
nohup python3 main.py CROSS1_YILDRIM_SVC_90 classificar > CROSS1_YILDRIM_SVC_90.log 2>&1
nohup python3 main.py CROSS2_CIFAR_SVC_60 classificar > CROSS2_CIFAR_SVC_60.log 2>&1
nohup python3 main.py CROSS2_CIFAR_SVC_70 classificar > CROSS2_CIFAR_SVC_70.log 2>&1
nohup python3 main.py CROSS2_CIFAR_SVC_80 classificar > CROSS2_CIFAR_SVC_80.log 2>&1
nohup python3 main.py CROSS2_CIFAR_SVC_90 classificar > CROSS2_CIFAR_SVC_90.log 2>&1
nohup python3 main.py CROSS2_NAZMUL_SVC_60 classificar > CROSS2_NAZMUL_SVC_60.log 2>&1 &